import type { Metadata } from "next";
import { Bitter, Crimson_Pro, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/auth/SessionProvider";

const bitter = Bitter({
  variable: "--font-bitter",
  subsets: ["latin"],
  weight: ["900"],
});

const crimsonPro = Crimson_Pro({
  variable: "--font-crimson-pro",
  subsets: ["latin"],
  weight: ["300", "400"],
  style: ["normal", "italic"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bitter.variable} ${crimsonPro.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className={`${crimsonPro.className} min-h-full flex flex-col bg-truth-bg text-truth-textLight`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
